<../mkconfig

LIB=libtk.a

OFILES=\
	after.$O\
	ebind.$O\
	event.$O\
	font.$O\
	grids.$O\
	image.$O\
	packr.$O\
	panel.$O\
	parse.$O\
	place.$O\
	ttk.$O\
	ttkwidg.$O\
	ttkprog.$O\
	ttknb.$O\
	ttkpane.$O\
	ttktree.$O\
	utils.$O\
	varbl.$O\
	windw.$O\
	xdata.$O\

HFILES=\
	$ROOT/include/tk.h\
	$ROOT/include/draw.h\

default:V:	all

<mkfile-$TKSTYLE
<$ROOT/mkfiles/mksyslib-$SHELLTYPE

ebind.$O:		$ROOT/include/interp.h
windw.$O:	canvs.h textw.h
