<../../../mkconfig

TARG=\
	dmview.dis\
	dmwm.dis\

LIBTARG=\
	drawmux.dis\

MODULES=\
	drawmux.m\
	drawoffs.m\

SYSMODULES=\
	arg.m\
	draw.m\
	sh.m\
	sys.m\
	tk.m\
	wmlib.m\

DISBIN=$ROOT/dis/wm
DISLIB=$ROOT/dis/lib

# Installed lib copies.  Precompute the pattern-substitution at parse time: mk
# does not expand ${var:%=%} inside a recipe, where it would reach the shell
# verbatim and abort ("Bad substitution" under dash).
LIBINST=${LIBTARG:%=$DISLIB/%}

all:V:	$TARG $LIBTARG

install:V:	$DISBIN/dmview.dis $DISBIN/dmwm.dis $DISLIB/drawmux.dis

<$ROOT/mkfiles/mkdis

nuke:V:	nuke-lib

nuke-lib:V:
	rm -f $LIBINST

$DISLIB/%.dis:	%.dis
	mkdir -p $DISLIB && rm -f $DISLIB/$stem.dis && cp $stem.dis $DISLIB/$stem.dis
