<../../../../mkconfig

BIN=$ROOT/acme/edit

DIRS=\
	src\

TARG=\
	guide\
	readme\

BINTARG=${TARG:%=$BIN/%}

all:V:		$TARG

install:V:	$BINTARG

$BIN/guide : guide
	mkdir -p $BIN && rm -f $BIN/guide && cp guide $BIN/guide

$BIN/readme : readme
	mkdir -p $BIN && rm -f $BIN/readme && cp readme $BIN/readme

<$ROOT/mkfiles/mksubdirs